package com.cliniccore.audit.domain;

public enum AuditAction {
	LOGIN,
	REFRESH_TOKEN,
	CREATE_CLINIC,
	CREATE_PROFESSIONAL,
	CREATE_ROOM,
	CREATE_SERVICE,
	CREATE_PATIENT,
	READ_PATIENT,
	DEACTIVATE_PATIENT,
	CREATE_APPOINTMENT,
	RESCHEDULE_APPOINTMENT,
	CANCEL_APPOINTMENT,
	COMPLETE_APPOINTMENT,
	MARK_NO_SHOW,
	OPEN_EPISODE,
	CLOSE_EPISODE,
	ADD_SESSION_NOTE,
	CREATE_PACKAGE,
	ASSIGN_PACKAGE,
	CONSUME_PACKAGE_SESSION,
	CREATE_EXERCISE,
	ASSIGN_EXERCISE_PLAN,
	READ_DASHBOARD
}
